#  vim:ts=2:sts=2:sw=2:et
#
#  Author: Hari Sekhon
#  Date: 2020-03-27 17:37:46 +0000 (Fri, 27 Mar 2020)
#
#  https://github.com/harisekhon/bash-tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/harisekhon
#

version: '3'

services:
  gocd-server:
    image: gocd/gocd-server:v20.2.0
    ports:
      - 8153:8153
  gocd-agent:
    image: gocd/gocd-agent-ubuntu-18.04:v20.2.0
    # needs root to be able to install OS package dependencies - 'sudo' not installed
    user: root
    environment:
      GO_SERVER_URL: http://gocd-server:8153/go
